spring.application.name: recommendation-service

server.port: 7002
server.error.include-message: always

logging:
  level:
    root: INFO
    se.example: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    messageProcessor-in-0:
      destination: recommendations
      group: recommendationsGroup
      consumer:
        max-attempts: 3
        back-off-initial-interval: 1000
        back-off-max-interval: 10000
        back-off-multiplier: 2.0

spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.messageProcessor-in-0.consumer:
  enableDlq: true

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

spring.cloud.stream.kafka.binder:
  brokers: localhost
  defaultBrokerPort: 9092

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db


app.eureka-server: localhost
app.eureka-username: u
app.eureka-password: p

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
app.eureka-server: eureka
spring.config.activate.on-profile: docker
server.port: 8080
spring.cloud.stream.kafka.binder.brokers: broker
spring.data.mongodb.host: mongodb